import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { query, libraryContext } = req.body;

  if (!query) {
    return res.status(400).json({ error: 'Query is required' });
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `You are Demic_AI, an expert academic assistant for Michael Okpara University of Agriculture, Umudike (MOUAU).

STUDENT OUESTION: "${query}"

MOUAU COURSE LIBRARY CONTEXT:
${libraryContext}

INSTRUCTIONS:
1. Provide a direct, helpful, and academic answer to the student's question.
2. If the student's question directly relates to any of the courses listed in the MOUAU COURSE LIBRARY CONTEXT above, you MUST explicitly recommend that they read that document (e.g., "For more details, please refer to the uploaded document: [Course Code] - [Course Title] uploaded by [Lecturer Name]").
3. If the question is general or not found in the library, answer the question accurately using your general academic knowledge, but briefly mention that there are currently no specific lecture notes on this exact topic in the library.
4. Keep the response concise, formatted beautifully in Markdown, and easy to read.
5. End your response with the exact signature phrase: "Generated by Demic_AI" on a new line.`
    });

    const textResponse = response.text || "";
    return res.status(200).json({ answer: textResponse });

  } catch (error: any) {
    const isInvalidKey = error?.status === 400 || error?.message?.includes('API key') || error?.message?.includes('API_KEY_INVALID');
    
    if (!isInvalidKey) {
      console.error("AI Chat Error:", error);
    } else {
      console.warn("AI Chat Warning: Missing or Invalid API Key.");
    }

    const errorMessage = isInvalidKey
      ? "⚠️ **API Configuration Error**\nYour Gemini API key is either invalid or missing. If you have deployed this project to Vercel, please navigate to your Vercel Dashboard -> Settings -> Environment Variables, and ensure `GEMINI_API_KEY` is set perfectly with no extra spaces or quotes."
      : "Sorry, I am currently unreachable due to a technical error. Please try again later.";
      
    // Ensure we always return 200 inside chat so it displays cleanly as the AI's response instead of failing
    return res.status(200).json({ answer: errorMessage });
  }
}
