import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { query, libraryContext } = req.body;

  if (!query) {
    return res.status(400).json({ error: 'Query is required' });
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: `You are Demic_AI, an expert academic assistant for Michael Okpara University of Agriculture, Umudike (MOUAU).

STUDENT OUESTION: "${query}"

MOUAU COURSE LIBRARY CONTEXT:
${libraryContext}

INSTRUCTIONS:
1. Provide a direct, helpful, and academic answer to the student's question.
2. If the student's question directly relates to any of the courses listed in the MOUAU COURSE LIBRARY CONTEXT above, you MUST explicitly recommend that they read that document (e.g., "For more details, please refer to the uploaded document: [Course Code] - [Course Title] uploaded by [Lecturer Name]").
3. If the question is general or not found in the library, answer the question accurately using your general academic knowledge, but briefly mention that there are currently no specific lecture notes on this exact topic in the library.
4. Keep the response concise, formatted beautifully in Markdown, and easy to read.
5. End your response with the exact signature phrase: "Generated by Demic_AI" on a new line.`
    });

    return res.status(200).json({ answer: response.text });

  } catch (error: any) {
    console.error("AI Chat Error:", error);
    return res.status(500).json({ 
      error: 'Failed to generate AI response.', 
      details: error.message 
    });
  }
}
