import { GoogleGenAI, Type } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export const config = {
  maxDuration: 60, // Set maximum duration for Vercel Serverless Function to allow downloading large PDFs
};

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { fileUrl, courseCode, courseTitle, query, history, libraryContext } = req.body;

  if (!fileUrl || !query) {
    return res.status(400).json({ error: 'File URL and query are required' });
  }

  try {
    // 1. Fetch file with a strict timeout so Vercel doesn't kill the function purely on fetching
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 8000); // 8 seconds max download time
    
    let base64Data = null;
    try {
      const fileResponse = await fetch(fileUrl, { signal: controller.signal });
      if (fileResponse.ok) {
        const arrayBuffer = await fileResponse.arrayBuffer();
        base64Data = Buffer.from(arrayBuffer).toString('base64');
      }
    } catch (fetchErr) {
      console.warn("Could not fetch PDF in time, falling back to library context.", fetchErr);
    } finally {
      clearTimeout(timeoutId);
    }

    const historyText = (history || []).map((msg: any) => `${msg.role === 'user' ? 'Student' : 'Demic_AI'}: ${msg.text}`).join('\n\n');

    const parts: any[] = [
      {
        text: `You are Demic_AI, an expert academic assistant for MOUAU.
I am providing you with context about the current course document: ${courseCode} - ${courseTitle}.

MOUAU COURSE LIBRARY (Other documents uploaded by lecturers):
${libraryContext || "(No other materials linked)"}

CHAT HISTORY:
${historyText || "(No previous history)"}

STUDENT QUESTION: "${query}"

INSTRUCTIONS:
1. Answer the student's question accurately. If I attached the PDF document, use it as your strict primary source of truth.
2. If the answer exists in the current document context, answer it directly and thoroughly without explaining that you read it in the document. Do not start sentences with "According to the document". Just give the facts directly as the tutor.
3. If the answer is NOT in the current document, OR if another document in the MOUAU COURSE LIBRARY represents the subject better, you MUST reference that specific course code and title (e.g., "This isn't fully covered in your current document, but you can find this detailed in [Course Code] - [Course Title]").
4. If it's a general question not found anywhere, answer it correctly acting as a brilliant tutor. Do not mention that the lecture notes aren't available unless specifically asked "is this in the document".
5. Keep your answer direct, helpful, and concise. Format beautifully in markdown.
6. End your response with the exact signature: "Generated by Demic_AI" on a new line.`
      }
    ];

    // Only attach the huge PDF if we successfully fetched it
    if (base64Data) {
      parts.push({
        inlineData: {
          mimeType: "application/pdf",
          data: base64Data
        }
      });
    }

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: { parts }
    });

    const textResponse = response.text || "";
    return res.status(200).json({ answer: textResponse });

  } catch (error: any) {
    const isInvalidKey = error?.status === 400 || error?.message?.includes('API key') || error?.message?.includes('API_KEY_INVALID');
    if (!isInvalidKey) console.error("AI Doc Chat Error:", error);
    else console.warn("AI Doc Chat Warning: Missing or Invalid API Key.");

    return res.status(200).json({ 
      answer: isInvalidKey 
        ? "⚠️ **API Configuration Error**\nYour Gemini API key is missing or invalid. Please check Vercel environment variables." 
        : "Sorry, I encountered an error while processing this request. Please try again."
    });
  }
}
